owner: StreamlinersNZ 
repo: UptimeMonitor 

sites:
  - name: Streamliners
    url: https://www.streamliners.com/
    icon: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/streamliners-logo.svg
  - name: HealthPathways Hub
    url: https://hub.healthpathways.com/
    icon: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/healthPathways-logo.svg
    followRedirects: true
    maxRedirects: 5

status-website:
  # Custom domain for HealthPathways status page
  # cname: status.healthpathways.org Uncomment if using the custom domain
  baseUrl: /UptimeMonitor  # Only needed if not using custom domain
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/streamliners-logo.svg
  name: HealthPathways System Status
  introTitle: "**HealthPathways System Status**"
  introMessage: Real-time monitoring of Streamliners and HealthPathways services. This status page is powered by [Upptime](https://upptime.js.org).
  navbar:
    - title: Status
      href: /
    - title: Streamliners
      href: https://www.streamliners.com/
    - title: HealthPathways
      href: https://www.streamliners.com/

# Security: Issues are automatically created for downtime incidents
# Only repository collaborators can comment on issues
# See https://upptime.js.org/docs/configuration
