owner: StreamlinersNZ 
repo: UptimeMonitor
branch: main 

sites:
  - name: Streamliners
    url: https://www.streamliners.com/
    icon: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/streamliners-logo.svg
  - name: HealthPathways Hub
    url: https://hub.healthpathwayscommunity.org/
    icon: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/healthPathways-logo.svg
    followRedirects: true
    timeout: 30000
    maxRedirects: 5
  - name: Dot
    url: https://admin.healthpathwayscommunity.org/
    icon: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/healthPathways-logo.svg
    followRedirects: true
    timeout: 30000
    maxRedirects: 5

status-website:
  # Custom domain for HealthPathways status page
  # cname: status.healthpathways.org Uncomment if using the custom domain
  baseUrl: /UptimeMonitor  # Only needed if not using custom domain
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/streamliners-logo.svg
  name: HealthPathways System Status
  introTitle: "**HealthPathways System Status**"
  introMessage: Real-time monitoring of Streamliners and HealthPathways services.
  description: "Uptime monitoring and status page for Streamliners and HealthPathways services, powered by Upptime."
  keywords: ["uptime", "monitoring", "status", "healthpathways", "streamliners", "reliability"]
  author: "Streamliners NZ Ltd"
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/$OWNER/$REPO/HEAD/assets/streamliners-theme.css
  css: |
    /* Test inline CSS to verify theme loading */
    body { background-color: #F8F5F0 !important; }
    .navbar { background-color: #421B30 !important; }
    .navbar-brand, .navbar-nav .nav-link { color: white !important; }
  navbar:
    - title: Streamliners
      href: https://www.streamliners.com/
    - title: Hub
      href: https://hub.healthpathwayscommunity.org/
    - title: Dot
      href: https://admin.healthpathwayscommunity.org/

# Security: Issues are automatically created for downtime incidents
# Only repository collaborators can comment on issues
# See https://upptime.js.org/docs/configuration

# Disable topics to avoid permission issues
skipTopics: true
